package com.s18110304.recycler_view;

import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class CountryRepository {
   private CountryRepository() {}

   public static List<Country> getOriginalCountryList() {
      final List<Country> countries = Arrays.asList(
              new Country("Afghanistan", "93", "AF / AFG", R.drawable.flag_af),
              new Country("Albania", "355", "AL / ALB", R.drawable.flag_al),
              new Country("Algeria", "213", "DZ / DZA", R.drawable.flag_dz),
              new Country("American Samoa", "1-684", "AS / ASM", R.drawable.flag_as),
              new Country("Andorra", "376", "AD / AND", R.drawable.flag_ad),
              new Country("Angola", "244", "AO / AGO", R.drawable.flag_ao),
              new Country("Anguilla", "1-264", "AI / AIA", R.drawable.flag_ai),
              new Country("Antigua and Barbuda", "1-268", "AG / ATG", R.drawable.flag_ag),
              new Country("Argentina", "54", "AR / ARG", R.drawable.flag_ar),
              new Country("Armenia", "374", "AM / ARM", R.drawable.flag_am),
              new Country("Aruba", "297", "AW / ABW", R.drawable.flag_aw),
              new Country("Australia", "61", "AU / AUS", R.drawable.flag_au),
              new Country("Austria", "43", "AT / AUT", R.drawable.flag_at),
              new Country("Azerbaijan", "994", "AZ / AZE", R.drawable.flag_az),
              new Country("Bahamas", "1-242", "BS / BHS", R.drawable.flag_bs),
              new Country("Bahrain", "973", "BH / BHR", R.drawable.flag_bh),
              new Country("Bangladesh", "880", "BD / BGD", R.drawable.flag_bd),
              new Country("Barbados", "1-246", "BB / BRB", R.drawable.flag_bb),
              new Country("Belarus", "375", "BY / BLR", R.drawable.flag_by),
              new Country("Belgium", "32", "BE / BEL", R.drawable.flag_be),
              new Country("Belize", "501", "BZ / BLZ", R.drawable.flag_bz),
              new Country("Benin", "229", "BJ / BEN", R.drawable.flag_bj),
              new Country("Bermuda", "1-441", "BM / BMU", R.drawable.flag_bm),
              new Country("Bhutan", "975", "BT / BTN", R.drawable.flag_bt),
              new Country("Bolivia", "591", "BO / BOL", R.drawable.flag_bo),
              new Country("Bosnia and Herzegovina", "387", "BA / BIH", R.drawable.flag_ba),
              new Country("Botswana", "267", "BW / BWA", R.drawable.flag_bw),
              new Country("Brazil", "55", "BR / BRA", R.drawable.flag_br),
              new Country("British Indian Ocean Territory", "246", "IO / IOT", R.drawable.flag_io),
              new Country("British Virgin Islands", "1-284", "VG / VGB", R.drawable.flag_vg),
              new Country("Brunei", "673", "BN / BRN", R.drawable.flag_bn),
              new Country("Bulgaria", "359", "BG / BGR", R.drawable.flag_bg),
              new Country("Burkina Faso", "226", "BF / BFA", R.drawable.flag_bf),
              new Country("Myanmar", "95", "MM / MMR", R.drawable.flag_mm),
              new Country("Burundi", "257", "BI / BDI", R.drawable.flag_bi),
              new Country("Cambodia", "855", "KH / KHM", R.drawable.flag_kh),
              new Country("Cameroon", "237", "CM / CMR", R.drawable.flag_cm),
              new Country("Canada", "1", "CA / CAN", R.drawable.flag_ca),
              new Country("Cape Verde", "238", "CV / CPV", R.drawable.flag_cv),
              new Country("Cayman Islands", "1-345", "KY / CYM", R.drawable.flag_ky),
              new Country("Central African Republic", "236", "CF / CAF", R.drawable.flag_cf),
              new Country("Chad", "235", "TD / TCD", R.drawable.flag_td),
              new Country("Chile", "56", "CL / CHL", R.drawable.flag_cl),
              new Country("China", "86", "CN / CHN", R.drawable.flag_cn),
              new Country("Christmas Island", "61", "CX / CXR", R.drawable.flag_cx),
              new Country("Cocos Islands", "61", "CC / CCK", R.drawable.flag_cc),
              new Country("Colombia", "57", "CO / COL", R.drawable.flag_co),
              new Country("Comoros", "269", "KM / COM", R.drawable.flag_km),
              new Country("Republic of the Congo", "242", "CG / COG", R.drawable.flag_cg),
              new Country("Democratic Republic of the Congo", "243", "CD / COD", R.drawable.flag_cd),
              new Country("Cook Islands", "682", "CK / COK", R.drawable.flag_ck),
              new Country("Costa Rica", "506", "CR / CRI", R.drawable.flag_cr),
              new Country("Croatia", "385", "HR / HRV", R.drawable.flag_hr),
              new Country("Cuba", "53", "CU / CUB", R.drawable.flag_cu),
              new Country("Curacao", "599", "CW / CUW", R.drawable.flag_cw),
              new Country("Cyprus", "357", "CY / CYP", R.drawable.flag_cy),
              new Country("Czech Republic", "420", "CZ / CZE", R.drawable.flag_cz),
              new Country("Denmark", "45", "DK / DNK", R.drawable.flag_dk),
              new Country("Djibouti", "253", "DJ / DJI", R.drawable.flag_dj),
              new Country("Dominica", "1-767", "DM / DMA", R.drawable.flag_dm),
              new Country("Dominican Republic", "1-809, 1-829, 1-849", "DO / DOM", R.drawable.flag_do),
              new Country("East Timor", "670", "TL / TLS", R.drawable.flag_tl),
              new Country("Ecuador", "593", "EC / ECU", R.drawable.flag_ec),
              new Country("Egypt", "20", "EG / EGY", R.drawable.flag_eg),
              new Country("El Salvador", "503", "SV / SLV", R.drawable.flag_sv),
              new Country("Equatorial Guinea", "240", "GQ / GNQ", R.drawable.flag_gq),
              new Country("Eritrea", "291", "ER / ERI", R.drawable.flag_er),
              new Country("Estonia", "372", "EE / EST", R.drawable.flag_ee),
              new Country("Ethiopia", "251", "ET / ETH", R.drawable.flag_et),
              new Country("Falkland Islands", "500", "FK / FLK", R.drawable.flag_fk),
              new Country("Faroe Islands", "298", "FO / FRO", R.drawable.flag_fo),
              new Country("Fiji", "679", "FJ / FJI", R.drawable.flag_fj),
              new Country("Finland", "358", "FI / FIN", R.drawable.flag_fi),
              new Country("France", "33", "FR / FRA", R.drawable.flag_fr),
              new Country("French Polynesia", "689", "PF / PYF", R.drawable.flag_pf),
              new Country("Gabon", "241", "GA / GAB", R.drawable.flag_ga),
              new Country("Gambia", "220", "GM / GMB", R.drawable.flag_gm),
              new Country("Georgia", "995", "GE / GEO", R.drawable.flag_ge),
              new Country("Germany", "49", "DE / DEU", R.drawable.flag_de),
              new Country("Ghana", "233", "GH / GHA", R.drawable.flag_gh),
              new Country("Gibraltar", "350", "GI / GIB", R.drawable.flag_gi),
              new Country("Greece", "30", "GR / GRC", R.drawable.flag_gr),
              new Country("Greenland", "299", "GL / GRL", R.drawable.flag_gl),
              new Country("Grenada", "1-473", "GD / GRD", R.drawable.flag_gd),
              new Country("Guam", "1-671", "GU / GUM", R.drawable.flag_gu),
              new Country("Guatemala", "502", "GT / GTM", R.drawable.flag_gt),
              new Country("Guernsey", "44-1481", "GG / GGY", R.drawable.flag_gg),
              new Country("Guinea", "224", "GN / GIN", R.drawable.flag_gn),
              new Country("Guinea-Bissau", "245", "GW / GNB", R.drawable.flag_gw),
              new Country("Guyana", "592", "GY / GUY", R.drawable.flag_gy),
              new Country("Haiti", "509", "HT / HTI", R.drawable.flag_ht),
              new Country("Honduras", "504", "HN / HND", R.drawable.flag_hn),
              new Country("Hong Kong", "852", "HK / HKG", R.drawable.flag_hk),
              new Country("Hungary", "36", "HU / HUN", R.drawable.flag_hu),
              new Country("Iceland", "354", "IS / ISL", R.drawable.flag_is),
              new Country("India", "91", "IN / IND", R.drawable.flag_in),
              new Country("Indonesia", "62", "ID / IDN", R.drawable.flag_id),
              new Country("Iran", "98", "IR / IRN", R.drawable.flag_ir),
              new Country("Iraq", "964", "IQ / IRQ", R.drawable.flag_iq),
              new Country("Ireland", "353", "IE / IRL", R.drawable.flag_ie),
              new Country("Isle of Man", "44-1624", "IM / IMN", R.drawable.flag_im),
              new Country("Israel", "972", "IL / ISR", R.drawable.flag_il),
              new Country("Italy", "39", "IT / ITA", R.drawable.flag_it),
              new Country("Ivory Coast", "225", "CI / CIV", R.drawable.flag_ci),
              new Country("Jamaica", "1-876", "JM / JAM", R.drawable.flag_jm),
              new Country("Japan", "81", "JP / JPN", R.drawable.flag_jp),
              new Country("Jersey", "44-1534", "JE / JEY", R.drawable.flag_je),
              new Country("Jordan", "962", "JO / JOR", R.drawable.flag_jo),
              new Country("Kazakhstan", "7", "KZ / KAZ", R.drawable.flag_kz),
              new Country("Kenya", "254", "KE / KEN", R.drawable.flag_ke),
              new Country("Kiribati", "686", "KI / KIR", R.drawable.flag_ki),
              new Country("Kosovo", "383", "XK / XKX", R.drawable.flag_xk),
              new Country("Kuwait", "965", "KW / KWT", R.drawable.flag_kw),
              new Country("Kyrgyzstan", "996", "KG / KGZ", R.drawable.flag_kg),
              new Country("Laos", "856", "LA / LAO", R.drawable.flag_la),
              new Country("Latvia", "371", "LV / LVA", R.drawable.flag_lv),
              new Country("Lebanon", "961", "LB / LBN", R.drawable.flag_lb),
              new Country("Lesotho", "266", "LS / LSO", R.drawable.flag_ls),
              new Country("Liberia", "231", "LR / LBR", R.drawable.flag_lr),
              new Country("Libya", "218", "LY / LBY", R.drawable.flag_ly),
              new Country("Liechtenstein", "423", "LI / LIE", R.drawable.flag_li),
              new Country("Lithuania", "370", "LT / LTU", R.drawable.flag_lt),
              new Country("Luxembourg", "352", "LU / LUX", R.drawable.flag_lu),
              new Country("Macau", "853", "MO / MAC", R.drawable.flag_mo),
              new Country("Macedonia", "389", "MK / MKD", R.drawable.flag_mk),
              new Country("Madagascar", "261", "MG / MDG", R.drawable.flag_mg),
              new Country("Malawi", "265", "MW / MWI", R.drawable.flag_mw),
              new Country("Malaysia", "60", "MY / MYS", R.drawable.flag_my),
              new Country("Maldives", "960", "MV / MDV", R.drawable.flag_mv),
              new Country("Mali", "223", "ML / MLI", R.drawable.flag_ml),
              new Country("Malta", "356", "MT / MLT", R.drawable.flag_mt),
              new Country("Marshall Islands", "692", "MH / MHL", R.drawable.flag_mh),
              new Country("Mauritania", "222", "MR / MRT", R.drawable.flag_mr),
              new Country("Mauritius", "230", "MU / MUS", R.drawable.flag_mu),
              new Country("Mayotte", "262", "YT / MYT", R.drawable.flag_yt),
              new Country("Mexico", "52", "MX / MEX", R.drawable.flag_mx),
              new Country("Micronesia", "691", "FM / FSM", R.drawable.flag_fm),
              new Country("Moldova", "373", "MD / MDA", R.drawable.flag_md),
              new Country("Monaco", "377", "MC / MCO", R.drawable.flag_mc),
              new Country("Mongolia", "976", "MN / MNG", R.drawable.flag_mn),
              new Country("Montenegro", "382", "ME / MNE", R.drawable.flag_me),
              new Country("Montserrat", "1-664", "MS / MSR", R.drawable.flag_ms),
              new Country("Morocco", "212", "MA / MAR", R.drawable.flag_ma),
              new Country("Mozambique", "258", "MZ / MOZ", R.drawable.flag_mz),
              new Country("Namibia", "264", "NA / NAM", R.drawable.flag_na),
              new Country("Nauru", "674", "NR / NRU", R.drawable.flag_nr),
              new Country("Nepal", "977", "NP / NPL", R.drawable.flag_np),
              new Country("Netherlands", "31", "NL / NLD", R.drawable.flag_nl),
              new Country("New Caledonia", "687", "NC / NCL", R.drawable.flag_nc),
              new Country("New Zealand", "64", "NZ / NZL", R.drawable.flag_nz),
              new Country("Nicaragua", "505", "NI / NIC", R.drawable.flag_ni),
              new Country("Niger", "227", "NE / NER", R.drawable.flag_ne),
              new Country("Nigeria", "234", "NG / NGA", R.drawable.flag_ng),
              new Country("Niue", "683", "NU / NIU", R.drawable.flag_nu),
              new Country("Northern Mariana Islands", "1-670", "MP / MNP", R.drawable.flag_mp),
              new Country("North Korea", "850", "KP / PRK", R.drawable.flag_kp),
              new Country("Norway", "47", "NO / NOR", R.drawable.flag_no),
              new Country("Oman", "968", "OM / OMN", R.drawable.flag_om),
              new Country("Pakistan", "92", "PK / PAK", R.drawable.flag_pk),
              new Country("Palau", "680", "PW / PLW", R.drawable.flag_pw),
              new Country("Palestine", "970", "PS / PSE", R.drawable.flag_ps),
              new Country("Panama", "507", "PA / PAN", R.drawable.flag_pa),
              new Country("Papua New Guinea", "675", "PG / PNG", R.drawable.flag_pg),
              new Country("Paraguay", "595", "PY / PRY", R.drawable.flag_py),
              new Country("Peru", "51", "PE / PER", R.drawable.flag_pe),
              new Country("Philippines", "63", "PH / PHL", R.drawable.flag_ph),
              new Country("Pitcairn", "64", "PN / PCN", R.drawable.flag_pn),
              new Country("Poland", "48", "PL / POL", R.drawable.flag_pl),
              new Country("Portugal", "351", "PT / PRT", R.drawable.flag_pt),
              new Country("Puerto Rico", "1-787, 1-939", "PR / PRI", R.drawable.flag_pr),
              new Country("Qatar", "974", "QA / QAT", R.drawable.flag_qa),
              new Country("Reunion", "262", "RE / REU", R.drawable.flag_re),
              new Country("Romania", "40", "RO / ROU", R.drawable.flag_ro),
              new Country("Russia", "7", "RU / RUS", R.drawable.flag_ru),
              new Country("Rwanda", "250", "RW / RWA", R.drawable.flag_rw),
              new Country("Saint Barthelemy", "590", "BL / BLM", R.drawable.flag_bl),
              new Country("Samoa", "685", "WS / WSM", R.drawable.flag_ws),
              new Country("San Marino", "378", "SM / SMR", R.drawable.flag_sm),
              new Country("Sao Tome and Principe", "239", "ST / STP", R.drawable.flag_st),
              new Country("Saudi Arabia", "966", "SA / SAU", R.drawable.flag_sa),
              new Country("Senegal", "221", "SN / SEN", R.drawable.flag_sn),
              new Country("Serbia", "381", "RS / SRB", R.drawable.flag_rs),
              new Country("Seychelles", "248", "SC / SYC", R.drawable.flag_sc),
              new Country("Sierra Leone", "232", "SL / SLE", R.drawable.flag_sl),
              new Country("Singapore", "65", "SG / SGP", R.drawable.flag_sg),
              new Country("Sint Maarten", "1-721", "SX / SXM", R.drawable.flag_sx),
              new Country("Slovakia", "421", "SK / SVK", R.drawable.flag_sk),
              new Country("Slovenia", "386", "SI / SVN", R.drawable.flag_si),
              new Country("Solomon Islands", "677", "SB / SLB", R.drawable.flag_sb),
              new Country("Somalia", "252", "SO / SOM", R.drawable.flag_so),
              new Country("South Africa", "27", "ZA / ZAF", R.drawable.flag_za),
              new Country("South Korea", "82", "KR / KOR", R.drawable.flag_kr),
              new Country("South Sudan", "211", "SS / SSD", R.drawable.flag_ss),
              new Country("Spain", "34", "ES / ESP", R.drawable.flag_es),
              new Country("Sri Lanka", "94", "LK / LKA", R.drawable.flag_lk),
              new Country("Saint Helena", "290", "SH / SHN", R.drawable.flag_sh),
              new Country("Saint Kitts and Nevis", "1-869", "KN / KNA", R.drawable.flag_kn),
              new Country("Saint Lucia", "1-758", "LC / LCA", R.drawable.flag_lc),
              new Country("Saint Martin", "590", "MF / MAF", R.drawable.flag_mf),
              new Country("Saint Pierre and Miquelon", "508", "PM / SPM", R.drawable.flag_pm),
              new Country("Saint Vincent and the Grenadines", "1-784", "VC / VCT", R.drawable.flag_vc),
              new Country("Sudan", "249", "SD / SDN", R.drawable.flag_sd),
              new Country("Suriname", "597", "SR / SUR", R.drawable.flag_sr),
              new Country("Svalbard and Jan Mayen", "47", "SJ / SJM", R.drawable.flag_sj),
              new Country("Swaziland", "268", "SZ / SWZ", R.drawable.flag_sz),
              new Country("Sweden", "46", "SE / SWE", R.drawable.flag_se),
              new Country("Switzerland", "41", "CH / CHE", R.drawable.flag_ch),
              new Country("Syria", "963", "SY / SYR", R.drawable.flag_sy),
              new Country("Taiwan", "886", "TW / TWN", R.drawable.flag_tw),
              new Country("Tajikistan", "992", "TJ / TJK", R.drawable.flag_tj),
              new Country("Tanzania", "255", "TZ / TZA", R.drawable.flag_tz),
              new Country("Thailand", "66", "TH / THA", R.drawable.flag_th),
              new Country("Togo", "228", "TG / TGO", R.drawable.flag_tg),
              new Country("Tokelau", "690", "TK / TKL", R.drawable.flag_tk),
              new Country("Tonga", "676", "TO / TON", R.drawable.flag_to),
              new Country("Trinidad and Tobago", "1-868", "TT / TTO", R.drawable.flag_tt),
              new Country("Tunisia", "216", "TN / TUN", R.drawable.flag_tn),
              new Country("Turkey", "90", "TR / TUR", R.drawable.flag_tr),
              new Country("Turkmenistan", "993", "TM / TKM", R.drawable.flag_tm),
              new Country("Turks and Caicos Islands", "1-649", "TC / TCA", R.drawable.flag_tc),
              new Country("Tuvalu", "688", "TV / TUV", R.drawable.flag_tv),
              new Country("United Arab Emirates", "971", "AE / ARE", R.drawable.flag_ae),
              new Country("Uganda", "256", "UG / UGA", R.drawable.flag_ug),
              new Country("United Kingdom", "44", "GB / GBR", R.drawable.flag_gb),
              new Country("Ukraine", "380", "UA / UKR", R.drawable.flag_ua),
              new Country("Uruguay", "598", "UY / URY", R.drawable.flag_uy),
              new Country("United States", "1", "US / USA", R.drawable.flag_us),
              new Country("Uzbekistan", "998", "UZ / UZB", R.drawable.flag_uz),
              new Country("Vanuatu", "678", "VU / VUT", R.drawable.flag_vu),
              new Country("Vatican", "379", "VA / VAT", R.drawable.flag_va),
              new Country("Venezuela", "58", "VE / VEN", R.drawable.flag_ve),
              new Country("Vietnam", "84", "VN / VNM", R.drawable.flag_vn),
              new Country("U.S. Virgin Islands", "1-340", "VI / VIR", R.drawable.flag_vi),
              new Country("Wallis and Futuna", "681", "WF / WLF", R.drawable.flag_wf),
              new Country("Yemen", "967", "YE / YEM", R.drawable.flag_ye),
              new Country("Zambia", "260", "ZM / ZMB", R.drawable.flag_zm),
              new Country("Zimbabwe", "263", "ZW / ZWE", R.drawable.flag_zw)
      );

      return countries;
   }

   public static List<Country> getCountryListSortedByName() {
      final List<Country> countryList = getOriginalCountryList();
      Collections.sort(countryList, new Comparator<Country>() {
         @Override
         public int compare(Country a1, Country a2) {
            return a1.getCountryName().compareTo(a2.getCountryName());
         }
      });
      return countryList;
   }
   public static List<Country> getCountryListSortedByCode() {
      final List<Country> countryList = getOriginalCountryList();
      Collections.sort(countryList, new Comparator<Country>() {
         @Override
         public int compare(Country a1, Country a2) {
            return a1.getCountryCode().compareTo(a2.getCountryCode());
         }
      });
      return countryList;
   }
   public static List<Country> getCountryListSortedByIso() {
      final List<Country> countryList = getOriginalCountryList();
      Collections.sort(countryList, new Comparator<Country>() {
         @Override
         public int compare(Country a1, Country a2) {
            return a1.getIsoCode().compareTo(a2.getIsoCode());
         }
      });
      return countryList;
   }
}